services:
  - type: web
    name: superchampion
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
      - key: ORGANIZADOR_PIN
        sync: false
